#!/bin/bash

## Description: Install the theme's dependencies.
## Usage: npm [flags] [args]
## Example: "npm install or npm rebuild node-sass or npm run build or npm run watch"

cd /var/www/html/themes/custom/training_theme && npm $@
